import java.time.format.DateTimeFormatter;
import java.awt.*;
import javax.swing.*;
public class SeatSelection extends javax.swing.JFrame {

private final CShowing seans;
    public SeatSelection(CShowing seans) {
        this.seans=seans;
        initComponents();
        customComponents();
    }

    private void customComponents()
    {
        CManage<CMovie> movieManager= new CManage<> (CMovie.class);
        CMovie movie = (CMovie) movieManager.getById(seans.getIdMovie());
        if(movie!=null)
        {titleTxt.setText(movie.getTitle());}
        dateTxt.setText(seans.getDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")) 
    + " " + seans.getTime().format(DateTimeFormatter.ofPattern("HH:mm")));
        ImageIcon cover = new ImageIcon(getClass().getResource("/Image/gladiator.jpg"));
        cover_l.setIcon(cover);

       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sideInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cover_l = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        titleTxt = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        seatsPanel = new javax.swing.JPanel();
        seatA1 = new javax.swing.JToggleButton();
        seatA12 = new javax.swing.JToggleButton();
        seatA13 = new javax.swing.JToggleButton();
        seatA14 = new javax.swing.JToggleButton();
        seatA15 = new javax.swing.JToggleButton();
        seatA16 = new javax.swing.JToggleButton();
        seatA17 = new javax.swing.JToggleButton();
        seatA18 = new javax.swing.JToggleButton();
        seatA19 = new javax.swing.JToggleButton();
        seatA20 = new javax.swing.JToggleButton();
        seatA21 = new javax.swing.JToggleButton();
        seatA22 = new javax.swing.JToggleButton();
        seatA23 = new javax.swing.JToggleButton();
        seatA24 = new javax.swing.JToggleButton();
        seatA25 = new javax.swing.JToggleButton();
        seatA26 = new javax.swing.JToggleButton();
        seatA27 = new javax.swing.JToggleButton();
        seatA28 = new javax.swing.JToggleButton();
        seatA29 = new javax.swing.JToggleButton();
        seatA30 = new javax.swing.JToggleButton();
        seatA31 = new javax.swing.JToggleButton();
        seatA32 = new javax.swing.JToggleButton();
        seatA33 = new javax.swing.JToggleButton();
        seatA34 = new javax.swing.JToggleButton();
        seatA35 = new javax.swing.JToggleButton();
        seatA36 = new javax.swing.JToggleButton();
        seatA37 = new javax.swing.JToggleButton();
        seatA38 = new javax.swing.JToggleButton();
        seatA39 = new javax.swing.JToggleButton();
        seatA40 = new javax.swing.JToggleButton();
        seatA41 = new javax.swing.JToggleButton();
        seatA42 = new javax.swing.JToggleButton();
        seatA43 = new javax.swing.JToggleButton();
        seatA44 = new javax.swing.JToggleButton();
        seatA45 = new javax.swing.JToggleButton();
        seatA46 = new javax.swing.JToggleButton();
        seatA47 = new javax.swing.JToggleButton();
        seatA48 = new javax.swing.JToggleButton();
        seatA49 = new javax.swing.JToggleButton();
        seatA50 = new javax.swing.JToggleButton();
        seatA51 = new javax.swing.JToggleButton();
        seatA52 = new javax.swing.JToggleButton();
        seatA53 = new javax.swing.JToggleButton();
        seatA54 = new javax.swing.JToggleButton();
        seatA55 = new javax.swing.JToggleButton();
        seatA56 = new javax.swing.JToggleButton();
        seatA57 = new javax.swing.JToggleButton();
        seatA58 = new javax.swing.JToggleButton();
        seatA59 = new javax.swing.JToggleButton();
        seatA60 = new javax.swing.JToggleButton();
        seatA61 = new javax.swing.JToggleButton();
        seatA62 = new javax.swing.JToggleButton();
        seatA63 = new javax.swing.JToggleButton();
        seatA64 = new javax.swing.JToggleButton();
        seatA65 = new javax.swing.JToggleButton();
        seatNumber1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        seatNumber2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        sideInfo.setBackground(new java.awt.Color(75, 0, 130));

        jPanel1.setBackground(new java.awt.Color(74, 85, 199));

        cover_l.setBackground(new java.awt.Color(204, 204, 255));
        cover_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cover_l.setText("COVER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cover_l, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cover_l, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("TITLE");

        titleTxt.setForeground(new java.awt.Color(255, 255, 255));
        titleTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleTxt.setText("jLabel3");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("DATE");

        dateTxt.setForeground(new java.awt.Color(255, 255, 255));
        dateTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTxt.setText("jLabel3");

        javax.swing.GroupLayout sideInfoLayout = new javax.swing.GroupLayout(sideInfo);
        sideInfo.setLayout(sideInfoLayout);
        sideInfoLayout.setHorizontalGroup(
            sideInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideInfoLayout.createSequentialGroup()
                .addGroup(sideInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideInfoLayout.createSequentialGroup()
                        .addGroup(sideInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideInfoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sideInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel)))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sideInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideInfoLayout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sideInfoLayout.setVerticalGroup(
            sideInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        seatsPanel.setBackground(new java.awt.Color(255, 255, 255));

        seatA1.setText("seatA1");
        seatA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA1ActionPerformed(evt);
            }
        });

        seatA12.setText("seatA1");
        seatA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA12ActionPerformed(evt);
            }
        });

        seatA13.setText("seatA1");
        seatA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA13ActionPerformed(evt);
            }
        });

        seatA14.setText("seatA1");
        seatA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA14ActionPerformed(evt);
            }
        });

        seatA15.setText("seatA1");
        seatA15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA15ActionPerformed(evt);
            }
        });

        seatA16.setText("seatA1");
        seatA16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA16ActionPerformed(evt);
            }
        });

        seatA17.setText("seatA1");
        seatA17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA17ActionPerformed(evt);
            }
        });

        seatA18.setText("seatA1");
        seatA18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA18ActionPerformed(evt);
            }
        });

        seatA19.setText("seatA1");
        seatA19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA19ActionPerformed(evt);
            }
        });

        seatA20.setText("seatA1");
        seatA20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA20ActionPerformed(evt);
            }
        });

        seatA21.setText("seatA1");
        seatA21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA21ActionPerformed(evt);
            }
        });

        seatA22.setText("seatA1");
        seatA22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA22ActionPerformed(evt);
            }
        });

        seatA23.setText("seatA1");
        seatA23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA23ActionPerformed(evt);
            }
        });

        seatA24.setText("seatA1");
        seatA24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA24ActionPerformed(evt);
            }
        });

        seatA25.setText("seatA1");
        seatA25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA25ActionPerformed(evt);
            }
        });

        seatA26.setText("seatA1");
        seatA26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA26ActionPerformed(evt);
            }
        });

        seatA27.setText("seatA1");
        seatA27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA27ActionPerformed(evt);
            }
        });

        seatA28.setText("seatA1");
        seatA28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA28ActionPerformed(evt);
            }
        });

        seatA29.setText("seatA1");
        seatA29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA29ActionPerformed(evt);
            }
        });

        seatA30.setText("seatA1");
        seatA30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA30ActionPerformed(evt);
            }
        });

        seatA31.setText("seatA1");
        seatA31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA31ActionPerformed(evt);
            }
        });

        seatA32.setText("seatA1");
        seatA32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA32ActionPerformed(evt);
            }
        });

        seatA33.setText("seatA1");
        seatA33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA33ActionPerformed(evt);
            }
        });

        seatA34.setText("seatA1");
        seatA34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA34ActionPerformed(evt);
            }
        });

        seatA35.setText("seatA1");
        seatA35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA35ActionPerformed(evt);
            }
        });

        seatA36.setText("seatA1");
        seatA36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA36ActionPerformed(evt);
            }
        });

        seatA37.setText("seatA1");
        seatA37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA37ActionPerformed(evt);
            }
        });

        seatA38.setText("seatA1");
        seatA38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA38ActionPerformed(evt);
            }
        });

        seatA39.setText("seatA1");
        seatA39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA39ActionPerformed(evt);
            }
        });

        seatA40.setText("seatA1");
        seatA40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA40ActionPerformed(evt);
            }
        });

        seatA41.setText("seatA1");
        seatA41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA41ActionPerformed(evt);
            }
        });

        seatA42.setText("seatA1");
        seatA42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA42ActionPerformed(evt);
            }
        });

        seatA43.setText("seatA1");
        seatA43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA43ActionPerformed(evt);
            }
        });

        seatA44.setText("seatA1");
        seatA44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA44ActionPerformed(evt);
            }
        });

        seatA45.setText("seatA1");
        seatA45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA45ActionPerformed(evt);
            }
        });

        seatA46.setText("seatA1");
        seatA46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA46ActionPerformed(evt);
            }
        });

        seatA47.setText("seatA1");
        seatA47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA47ActionPerformed(evt);
            }
        });

        seatA48.setText("seatA1");
        seatA48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA48ActionPerformed(evt);
            }
        });

        seatA49.setText("seatA1");
        seatA49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA49ActionPerformed(evt);
            }
        });

        seatA50.setText("seatA1");
        seatA50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA50ActionPerformed(evt);
            }
        });

        seatA51.setText("seatA1");
        seatA51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA51ActionPerformed(evt);
            }
        });

        seatA52.setText("seatA1");
        seatA52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA52ActionPerformed(evt);
            }
        });

        seatA53.setText("seatA1");
        seatA53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA53ActionPerformed(evt);
            }
        });

        seatA54.setText("seatA1");
        seatA54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA54ActionPerformed(evt);
            }
        });

        seatA55.setText("seatA1");
        seatA55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA55ActionPerformed(evt);
            }
        });

        seatA56.setText("seatA1");
        seatA56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA56ActionPerformed(evt);
            }
        });

        seatA57.setText("seatA1");
        seatA57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA57ActionPerformed(evt);
            }
        });

        seatA58.setText("seatA1");
        seatA58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA58ActionPerformed(evt);
            }
        });

        seatA59.setText("seatA1");
        seatA59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA59ActionPerformed(evt);
            }
        });

        seatA60.setText("seatA1");
        seatA60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA60ActionPerformed(evt);
            }
        });

        seatA61.setText("seatA1");
        seatA61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA61ActionPerformed(evt);
            }
        });

        seatA62.setText("seatA1");
        seatA62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA62ActionPerformed(evt);
            }
        });

        seatA63.setText("seatA1");
        seatA63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA63ActionPerformed(evt);
            }
        });

        seatA64.setText("seatA1");
        seatA64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA64ActionPerformed(evt);
            }
        });

        seatA65.setText("seatA1");
        seatA65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatA65ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seatsPanelLayout = new javax.swing.GroupLayout(seatsPanel);
        seatsPanel.setLayout(seatsPanelLayout);
        seatsPanelLayout.setHorizontalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatsPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(seatsPanelLayout.createSequentialGroup()
                        .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatsPanelLayout.createSequentialGroup()
                        .addComponent(seatA22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatsPanelLayout.createSequentialGroup()
                        .addComponent(seatA38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatsPanelLayout.createSequentialGroup()
                        .addComponent(seatA49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(seatsPanelLayout.createSequentialGroup()
                        .addComponent(seatA55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seatA62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        seatsPanelLayout.setVerticalGroup(
            seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(seatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatA63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("4");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("6");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("7");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("8");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("9");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("10");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("11");

        javax.swing.GroupLayout seatNumber1Layout = new javax.swing.GroupLayout(seatNumber1);
        seatNumber1.setLayout(seatNumber1Layout);
        seatNumber1Layout.setHorizontalGroup(
            seatNumber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatNumber1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        seatNumber1Layout.setVerticalGroup(
            seatNumber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatNumber1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatNumber1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("B");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("A");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("D");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("C");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("E");

        javax.swing.GroupLayout seatNumber2Layout = new javax.swing.GroupLayout(seatNumber2);
        seatNumber2.setLayout(seatNumber2Layout);
        seatNumber2Layout.setHorizontalGroup(
            seatNumber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatNumber2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seatNumber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        seatNumber2Layout.setVerticalGroup(
            seatNumber2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatNumber2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addGap(47, 47, 47)
                .addComponent(jLabel17)
                .addGap(48, 48, 48)
                .addComponent(jLabel16)
                .addGap(50, 50, 50)
                .addComponent(jLabel18)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(seatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seatNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(seatNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(seatNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(seatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ekran1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sideInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA1ActionPerformed

    private void seatA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA12ActionPerformed

    private void seatA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA13ActionPerformed

    private void seatA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA14ActionPerformed

    private void seatA15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA15ActionPerformed

    private void seatA16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA16ActionPerformed

    private void seatA17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA17ActionPerformed

    private void seatA18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA18ActionPerformed

    private void seatA19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA19ActionPerformed

    private void seatA20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA20ActionPerformed

    private void seatA21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA21ActionPerformed

    private void seatA22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA22ActionPerformed

    private void seatA23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA23ActionPerformed

    private void seatA24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA24ActionPerformed

    private void seatA25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA25ActionPerformed

    private void seatA26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA26ActionPerformed

    private void seatA27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA27ActionPerformed

    private void seatA28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA28ActionPerformed

    private void seatA29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA29ActionPerformed

    private void seatA30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA30ActionPerformed

    private void seatA31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA31ActionPerformed

    private void seatA32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA32ActionPerformed

    private void seatA33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA33ActionPerformed

    private void seatA34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA34ActionPerformed

    private void seatA35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA35ActionPerformed

    private void seatA36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA36ActionPerformed

    private void seatA37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA37ActionPerformed

    private void seatA38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA38ActionPerformed

    private void seatA39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA39ActionPerformed

    private void seatA40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA40ActionPerformed

    private void seatA41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA41ActionPerformed

    private void seatA42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA42ActionPerformed

    private void seatA43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA43ActionPerformed

    private void seatA44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA44ActionPerformed

    private void seatA45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA45ActionPerformed

    private void seatA46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA46ActionPerformed

    private void seatA47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA47ActionPerformed

    private void seatA48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA48ActionPerformed

    private void seatA49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA49ActionPerformed

    private void seatA50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA50ActionPerformed

    private void seatA51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA51ActionPerformed

    private void seatA52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA52ActionPerformed

    private void seatA53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA53ActionPerformed

    private void seatA54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA54ActionPerformed

    private void seatA55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA55ActionPerformed

    private void seatA56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA56ActionPerformed

    private void seatA57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA57ActionPerformed

    private void seatA58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA58ActionPerformed

    private void seatA59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA59ActionPerformed

    private void seatA60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA60ActionPerformed

    private void seatA61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA61ActionPerformed

    private void seatA62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA62ActionPerformed

    private void seatA63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA63ActionPerformed

    private void seatA64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA64ActionPerformed

    private void seatA65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatA65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatA65ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cover_l;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton seatA1;
    private javax.swing.JToggleButton seatA12;
    private javax.swing.JToggleButton seatA13;
    private javax.swing.JToggleButton seatA14;
    private javax.swing.JToggleButton seatA15;
    private javax.swing.JToggleButton seatA16;
    private javax.swing.JToggleButton seatA17;
    private javax.swing.JToggleButton seatA18;
    private javax.swing.JToggleButton seatA19;
    private javax.swing.JToggleButton seatA20;
    private javax.swing.JToggleButton seatA21;
    private javax.swing.JToggleButton seatA22;
    private javax.swing.JToggleButton seatA23;
    private javax.swing.JToggleButton seatA24;
    private javax.swing.JToggleButton seatA25;
    private javax.swing.JToggleButton seatA26;
    private javax.swing.JToggleButton seatA27;
    private javax.swing.JToggleButton seatA28;
    private javax.swing.JToggleButton seatA29;
    private javax.swing.JToggleButton seatA30;
    private javax.swing.JToggleButton seatA31;
    private javax.swing.JToggleButton seatA32;
    private javax.swing.JToggleButton seatA33;
    private javax.swing.JToggleButton seatA34;
    private javax.swing.JToggleButton seatA35;
    private javax.swing.JToggleButton seatA36;
    private javax.swing.JToggleButton seatA37;
    private javax.swing.JToggleButton seatA38;
    private javax.swing.JToggleButton seatA39;
    private javax.swing.JToggleButton seatA40;
    private javax.swing.JToggleButton seatA41;
    private javax.swing.JToggleButton seatA42;
    private javax.swing.JToggleButton seatA43;
    private javax.swing.JToggleButton seatA44;
    private javax.swing.JToggleButton seatA45;
    private javax.swing.JToggleButton seatA46;
    private javax.swing.JToggleButton seatA47;
    private javax.swing.JToggleButton seatA48;
    private javax.swing.JToggleButton seatA49;
    private javax.swing.JToggleButton seatA50;
    private javax.swing.JToggleButton seatA51;
    private javax.swing.JToggleButton seatA52;
    private javax.swing.JToggleButton seatA53;
    private javax.swing.JToggleButton seatA54;
    private javax.swing.JToggleButton seatA55;
    private javax.swing.JToggleButton seatA56;
    private javax.swing.JToggleButton seatA57;
    private javax.swing.JToggleButton seatA58;
    private javax.swing.JToggleButton seatA59;
    private javax.swing.JToggleButton seatA60;
    private javax.swing.JToggleButton seatA61;
    private javax.swing.JToggleButton seatA62;
    private javax.swing.JToggleButton seatA63;
    private javax.swing.JToggleButton seatA64;
    private javax.swing.JToggleButton seatA65;
    private javax.swing.JPanel seatNumber1;
    private javax.swing.JPanel seatNumber2;
    private javax.swing.JPanel seatsPanel;
    private javax.swing.JPanel sideInfo;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
